booklist/urls.py
from django.conf.urls import url,include
from . import views,rest_views
from django.conf.urls.static import static
from haystack.views import SearchView


urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^books_view$', rest_views.BooksView.as_view()),
    url(r'^books_get/(?P<pk>\d+)$', rest_views.BookView.as_view()),
    url(r'^vuetest/$', views.vuetest,name='vuetest'),

    url(r'^showhero/$', views.showhero, name='showhero'),
    url(r'^delhero/$', views.delhero, name='delhero'),
    url(r'^addhero/$', views.addhero, name='addhero'),
    url(r'^edithero/$', views.edithero, name='edithero'),
    # url(r'^heroinfo/<int:hid>', views.show_hero, name='show_hero'),
    url(r'^addbook/$', views.addbook, name='addbook'),
    url(r'^windowaddbook/$', views.windowaddbook, name='windowaddbook'),
    url(r'^windowaddbook2/$', views.windowaddbook2, name='windowaddbook2'),

    url(r'^showbooks/$', views.showbooks, name='showbooks'),
    url(r'^showbooks2/$', views.showbooks2, name='showbooks2'),
    url(r'^showbooks_pagehandle/$', views.showbooks_pagehandle, name='showbooks_pagehandle'),

    url(r'^delbook/$', views.delbook, name='delbook'),
    url(r'^editbook/(\d*)$', views.editbook, name='editbook'),
    url(r'^modelEditbook/$', views.modelEditbook, name='modelEditbook'),
    url(r'^test/$', views.test, name='test'),
    url(r'^getdata/$', views.getdata, name='getdata'),
    url(r'^bookhero/$', views.bookhero, name='bookhero'),
    url(r'^writer_list/$', views.WriterListView.as_view(), name='writer_list'),

    url(r'^addwriter/$', views.addwriter, name='addwriter'),
    url(r'^editwriter/$', views.editwriter, name='editwriter'),
    url(r'^getwriter/$', views.getwriter, name='getwriter'),
    url(r'^modal_addwriter/$', views.modal_addwriter, name='modal_addwriter'),
    url(r'^window/$', views.window, name='window'),
    url(r'^layout/$', views.layout, name='layout'),
    # url(r'^results/$', views.search, name='search'),
    url(r'search/$', SearchView(), name='haystack_search'),
    url(r'lvbooks/$', views.BooklistView.as_view(), name='booklist_view'),
    url(r'^query/$', views.search, name='search',),

    # url(r'^search/', include(('haystack.urls','haystack'),namespace='haystack')),

]

mysite/urls.py
from django.conf.urls import url, include

from django.contrib import admin

urlpatterns = [
    url(r'^booklist/', include(('booklist.urls', 'booklist'), namespace='booklist')),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include(('useradmin.urls', 'useradmin'), namespace='useradmin')),
    url(r'^mytest/', include(('mytest.urls', 'mytest'), namespace='mytest')),
    url(r'^bookdrf/', include(('bookdrf.urls', 'bookdrf'), namespace='bookdrf')),

]

useradmin/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'register$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    # url(r'^login2/$', views.login, name='login2'),
    url(r'^jsif/$', views.jsif, name='jsif'),
    url(r'^edituser/$', views.edituser, name='edituser'),
    url(r'^lf/$', views.login_form, name='login_form'),




]

booklist/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=20)
    # writer = models.CharField(max_length=20)
    press = models.CharField(max_length=20)
    date = models.DateField('出版日期')
    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Writer(models.Model):
    wname = models.CharField(max_length=20)
    wage = models.IntegerField()


class book_writer(models.Model):
    bid = models.IntegerField()
    wid = models.IntegerField()


class Organization(models.Model):
    orgname = models.CharField(max_length=20)
    district = models.CharField(max_length=20)
    scale = models.IntegerField(default=0)
    established_time = models.DateField('成立时间')

    def __str__(self):
        return self.name


class Hero(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    org = models.ForeignKey(Organization, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, db_column='hname')
    skill = models.CharField(max_length=20)

    # org = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=3)
    birth_date = models.DateField(blank=True, null=True)

booklist/forms.py
from django import forms
from haystack.forms import SearchForm

class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required=True)

    def search(self):
        datas = super(BlogSearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['querydata']:
            logger.info(self.cleaned_data['querydata'])
        return datas

booklist/views.py
from functools import wraps

from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView
import json
import pymysql
from .utils import sqlhandle
from .utils.pagehandle import PageInfo
from django.urls import reverse
from .models import *
from django.contrib.auth.decorators import login_required

from useradmin.views import check_login_cookie

import logging
# 设置打印日志的级别，level级别以上的日志会打印出
# level=logging.DEBUG 、INFO 、WARNING、ERROR、CRITICAL
logging.basicConfig(filename='log.txt',
                    filemode='a',
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s-%(funcName)s',
                    level=logging.DEBUG)


def vuetest(request):
    logging.debug(request)
    content = {'name':'Mike'}
    return render(request,'booklist/vuetest.html',content)



class WriterListView(ListView):
    model = Writer
    template_name= 'booklist/writer_list.html'
    context_object_name ='writer_list'
    queryset = Writer.objects.all()


def addwriter(request):
    if request.method == 'GET':
        btitle = sqlhandle.search('select * from booklist_book')
        return render(request, 'booklist/addwriter.html', {'btitle': btitle})
    else:
        wname = request.POST.get('wname')
        wage = request.POST.get('wage')
        bid = request.POST.getlist('bid')
        # print(wname,wage)
        wid = sqlhandle.update('insert into booklist_writer(wname,wage) values(%s,%s)', [wname, wage])

        for bid in bid:
            sqlhandle.update('insert into booklist_book_writer(bid,wid) values(%s,%s)', [bid, wid])
        return redirect('/booklist/showwriter/')


def editwriter(request):
    if request.method == 'GET':
        nid = request.GET.get('nid')
        writer = sqlhandle.getone('select * from booklist_writer where id=%s', [nid, ])
        bookid = sqlhandle.search(
            'select bid from booklist_book_writer where wid=%s', [nid, ])
        bookidlist = []
        for bid in bookid:
            bookidlist.append(bid['bid'])
        book = sqlhandle.search('select * from booklist_book')
        # print(bookidlist)
        return render(request, 'booklist/editwriter.html', {'writer': writer, 'book': book, 'bookidlist': bookidlist})

    else:
        nid = request.POST.get('nid')
        wname = request.POST.get('wname')
        wage = request.POST.get('wage')
        bookid = request.POST.getlist('bid')
        # print(bookid)
        sqlhandle.update('update booklist_writer set wname =%s,wage=%s where id=%s ', [wname, wage, nid])

        bid = sqlhandle.search('select bid from booklist_book_writer where wid=%s', [nid, ])
        bidlist = []
        for bid in bid:
            bidlist.append(bid['bid'])

        sqlhandle.update('delete from booklist_book_writer where wid=%s', [nid, ])

        for bookid in bookid:
            sqlhandle.update('insert into booklist_book_writer(bid,wid) values (%s,%s)', [bookid, nid])


        return redirect('/booklist/showwriter/')


def getwriter(request):
    import time
    time.sleep(0.5)
    writer = sqlhandle.search('select * from booklist_writer')
    return HttpResponse(json.dumps(writer))


def modal_addwriter(request):
    name = request.POST.get('name')
    age = request.POST.get('age')
    bid = request.POST.getlist('wid')
    wid = sqlhandle.update('insert into booklist_writer(wname,wage) values(%s,%s)', [name, age])
    print(wid)
    for bid in bid:
        sqlhandle.update('insert into booklist_book_writer(bid,wid) values(%s,%s)', [bid, wid])

    return HttpResponse('ok')

from useradmin.views import allowed_users

@check_login_cookie
@allowed_users(allowed_roles=['emp'])
def showhero(request):
    
    results = Hero.objects.all()
    # for i in results:
    #     print(i,i.skill,i.book,i.org.orgname)
    return render(request, 'booklist/showhero.html', {'results': results})


def delhero(request):
    nid = request.GET.get('nid')
    Hero.objects.get(id=nid).delete()
    return redirect('/booklist/showhero')


def addhero(request):
    if request.method == 'GET':
        conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='', database='bookstore',
                               charset='utf8')
        cursor = conn.cursor(cursor=pymysql.cursors.DictCursor)

        sqlbook = """select * from booklist_book;"""
        cursor.execute(sqlbook)
        book = cursor.fetchall()
        sqlorg = """select * from booklist_organization;"""
        cursor.execute(sqlorg)

        org = cursor.fetchall()

        content = {'book': book, 'org': org}
        cursor.close()
        conn.close()
        return render(request, 'booklist/addhero.html', content)

    else:
        # print(request.POST)
        hname = request.POST.get('hname')
        skill = request.POST.get('skill')
        bookid = request.POST.get('bookid')
        orgid = request.POST.get('orgid')
        print(len(hname))
        if len(hname) > 0:
            conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='', database='bookstore',
                                   charset='utf8')
            cursor = conn.cursor(cursor=pymysql.cursors.DictCursor)

            sql = """insert into booklist_hero(hname, skill, org_id, book_id) values(%s,%s,%s,%s)"""
            l = [hname, skill, orgid, bookid]
            # print(l)
            cursor.execute(sql, l)
            conn.commit()

            cursor.close()
            conn.close()
            # print(request.POST.get('title'))
            return redirect('/booklist/showhero/')

        else:
            return render(request, 'booklist/addhero.html', {'msg': '姓名不能为空'})


def edithero(request):
    if request.method == 'GET':
        nid = request.GET.get('nid')
        conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='', database='bookstore',
                               charset='utf8')
        cursor = conn.cursor(cursor=pymysql.cursors.DictCursor)
        cursor.execute(
            "select bh.id,bh.hname,bh.book_id,bh.org_id,bb.title,bo.orgname,bh.skill from booklist_book bb,booklist_hero bh,booklist_organization bo where bb.id = bh.book_id and bh.org_id=bo.id and bh.id=%s",
            [nid, ])
        hero = cursor.fetchone()
        cursor.execute("select * from booklist_book")
        book = cursor.fetchall()
        cursor.execute("select * from booklist_organization")
        org = cursor.fetchall()
        content = {'hero': hero, 'book': book, 'org': org}

        cursor.close()
        conn.close()
        return render(request, 'booklist/edithero.html', content)

    else:
        nid = request.GET.get('nid')
        hname = request.POST.get('hname')
        bookid = request.POST.get('bookid')
        skill = request.POST.get('skill')
        orgid = request.POST.get('orgid')
        # print(len(hname))
        if len(hname) > 0:
            conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='', database='test',
                                   charset='utf8')
            cursor = conn.cursor(cursor=pymysql.cursors.DictCursor)
            cursor.execute("update booklist_hero set hname = %s,skill = %s,org_id = %s,book_id = %s where id=%s",
                           [hname, skill, orgid, bookid, nid])
            conn.commit()
            cursor.close()
            conn.close()

            return redirect('/booklist/showhero/')

        else:
            return render(request, 'booklist/edithero.html', {'msg': 'name and skill cant be null'})



class BooklistView(ListView):
    model  = Book
    template_name = 'booklist/lvbooks.html'
    context_object_name  = 'booklist'
    queryset = Book.objects.all()
    # def getBooks(self,**args):
    #     books = Book.objects.all()
    #     return books

# def HeroInfo(request, hid):
#     h = Hero.objects.get(pk=hid)
#     context = {'h': h}
#     print(h)
#     return render(request, 'booklist/heroinfo.html', context)


def addbook(request):
    if request.method == 'GET':

        return render(request, 'booklist/addbook.html')
    else:
        # print(request.POST)
        title = request.POST.get('title')
        press = request.POST.get('press')
        date = request.POST.get('date')
        binfo = request.POST
        print('binfo=%s' % binfo)
        if len(title) > 0:
            Book.objects.create(title=title, press=press, date=date)

            return redirect('/booklist/showbooks_pagehandle/?page=1')
        else:
            return render(request, 'booklist/addbook.html', {'msg': '书名不能为空'})


def windowaddbook(request):
    print(123)
    title = request.POST.get('title')
    # writer = request.POST.get('writer')
    press = request.POST.get('press')
    date = request.POST.get('date')

    if len(title) > 0:
        conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='', database='bookstore',
                               charset='utf8')
        cursor = conn.cursor()

        sql = """insert into booklist_book(title, press, date) values(%s,%s,%s)"""
        l = (title, press, date)
        print(l)
        cursor.execute(sql, l)
        conn.commit()

        cursor.close()
        conn.close()
        return HttpResponse('OK')
    else:
        return HttpResponse('书籍名称不能为空')

@login_required()
def showbooks(request):
    results = Book.objects.all()
    # print(results)
    all_count = Book.objects.all().count()
    current_page = request.GET.get('page')
    page_info = PageInfo(current_page,all_count,10,'/booklist/showbooks/')
    booklist = Book.objects.all()[page_info.start():page_info.end()]
    # print(booklist)

    return render(request, 'booklist/showbooks.html', {'book': booklist,'page_info':page_info})

def editbook(request,nid):
    if request.method == 'GET':
        print(nid)

        book = Book.objects.get(id=nid)
        return render(request, 'booklist/editbook.html', {'book': book})

    else:

booklist/templates/booklist/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action="/booklist/addhero/">
   姓名:<input type='text' name='hname' /><br>
    技能:<input type='text' name='skill' /><br>
    所属书籍:
        <select name="bookid">
        {%for book in book%}
            <option value="{{book.id}}">{{book.title}}</option>
        {% endfor %}
        </select><br>
    帮派:
    <select name="orgid">
        {% for org in org %}
            <option value="{{org.id}}">{{org.orgname}}</option>
        {% endfor %}
    </select>
    <input type='submit' value='提交' />{{msg}}
</form>
</body>
</html>

booklist/templates/booklist/index.html
{% extends 'booklist/layout2.html' %}
{% load static %}
{% block bb %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<li>
    <a href="www.baidu.com">欢迎！</a>
</li>
{% endblock %}

booklist/templates/booklist/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/plugins/font-awesome-4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/static/css/commoncss.css">
    <script type="text/javascript" src="/static/js/myjs.js"></script>
</head>
<body>
    <div class="pg-header">
        <div class="person right" style="position: relative;padding: 0 15px;" >
            <img width="30" height="30" src="/static/images/person.jpg">
            <div class="personinfo">
                <a>个人资料</a><br>
                <a href="{% url 'useradmin:logout' %}">退出</a>
                <a href="{% url 'useradmin:login' %}">登录1</a>

            </div>
        </div>
        <div class="logo left">书籍后台管理系统</div>
        <div class="rmenus right">
            <a><i class="fa fa-commenting-o" aria-hidden="true"></i>消息</a>
            <a><i class="fa fa-envelope-o" aria-hidden="true"></i> 邮件</a>
        </div>
    </div>
    <div class="pg-body">
        <div class="menus right"></div>

        <div class="content">
            <ol class="breadcrumb">
              <li><a href="#">首页</a></li>
              <li><a href="#">书籍管理</a></li>
              <li class="active">添加书籍</li>
              <li>
                <div>
                    <form action="{% url 'booklist:search' %}" method="get">
                        <input type="text" name="q" id="keyword">
                        <input type="submit" value="查询" id="sbt" onclick="setkeyword();">
                    </form>
                </div>
              </li>
            </ol>
            {% block bb %}

            {% endblock %}
        </div>
    </div>

    <div class="pg-body">
        <div class="menus">
            <a href="/booklist/showbooks_pagehandle/?page=1">书籍管理</a>
            <a href="/booklist/writer_list/">作者管理</a>
            <a href="/booklist/showhero">英雄管理</a>
        </div>

    </div>

</body>
</html>

booklist/templates/booklist/layout2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/plugins/font-awesome-4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/static/css/commoncss.css">
</head>
<body>
    <div class="pg-header">
        <div class="person right" style="position: relative;padding: 0 15px;">
            <img width="30" height="30" src="/static/images/person.jpg">
            <div class="personinfo">
                <a>个人资料</a><br>
                <a href="{% url 'useradmin:logout' %}">退出</a>
                <a href="{% url 'useradmin:login' %}">登录</a>

            </div>
        </div>
        <div class="logo left">书籍后台管理系统</div>
        <div class="rmenus right">
            <a><i class="fa fa-commenting-o" aria-hidden="true"></i>消息</a>
            <a><i class="fa fa-envelope-o" aria-hidden="true"></i> 邮件</a>
        </div>
    </div>
    <div class="pg-body">
        <div class="menus right">cd</div>

        <div class="content">
            <ol class="breadcrumb">
              <li><a href="#">首页</a></li>
              <li><a href="#">书籍管理</a></li>
              <li class="active">添加书籍</li>
            </ol>
            <div>
                <form action="{% url 'booklist:search' %}" method="get">
                    <input type="text" name="q" id="keyword">
                    <input type="submit" value="查询" id="sbt" onclick="setkeyword();">
                </form>
            </div>

            {% block bb %}

            {% endblock %}
        </div>


    </div>

    <div class="pg-body">
        <div class="menus">
            <a>书籍管理</a>
            <a href="/booklist/writer_list/">作者管理</a>
            <a href="/booklist/showhero/">英雄管理</a>
        </div>

    </div>

</body>
</html>

booklist/templates/booklist/lvbooks.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{% for book in booklist %}
	{{book.title}}<br>
	{%endfor%}
</body>
</html>

booklist/templates/booklist/showbooks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/plugins/font-awesome-4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/static/css/commoncss.css">
</head>
<body>
    <div class="pg-header">
        <div class="person right" style="position: relative;padding: 0 15px;" >
            <img width="30" height="30" src="/static/images/person.jpg">
            <div class="personinfo">
                <a>个人资料</a><br>
                <a>退出</a>
            </div>
        </div>
        <div class="logo left">书籍后台管理系统</div>
        <div class="rmenus right">
            <a><i class="fa fa-commenting-o" aria-hidden="true"></i>消息</a>
            <a><i class="fa fa-envelope-o" aria-hidden="true"></i> 邮件</a>
        </div>
    </div>

    <div class="pg-body">
        <div class="menus right">cd</div>

        <div class="content">
            <ol class="breadcrumb">
              <li><a href="#">首页</a></li>
              <li><a href="#">书籍管理</a></li>
              <li class="active">添加书籍</li>
            </ol>
            <div>
                <h3><a href="/booklist/addbook">添加</a> | <a onclick="showModal();">对话框添加书籍</a></h3>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>书籍名称</th>
                            <th>出版社</th>
                            <th>出版时间</th>
                            <th>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;包含英雄</th>
                            <th>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;操作</th>
                        </tr>
                    </thead>
                </table>

                <table class="table">
                    {% for book in book %}
                    <thead>
                        <tr>
                            <td>{{book.id}}</td>
                            <td>{{book.title}}</td>
                            <td>{{book.press}}</td>
                            <td>{{book.date | date:'Y-m-d'}}</td>
                            <td><a href="/booklist/editbook/{{book.id}}">编辑</a>
                                |
                                <a onclick="modelEdit(this);">对话框编辑</a>
                                |
                                <a href="/booklist/delbook/?nid={{book.id}}">删除</a>
                                <br>
                            </td>

                        </tr>
                    </thead>
                    {% endfor %}
                </table>
                <nav aria-label="Page navigation">
                  <ul class="pagination">
                    <li>page={{ page_info.current_page }}
                      <a href="/booklist/showbooks/?page={{ page_info.current_page|add:-1 }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    <li>{{ page_info.pager | safe}}</li>
                    <li>
                      <a href="/booklist/showbooks/?page={{ page_info.current_page|add:1}}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    </li>
                  </ul>
                </nav>


                <div id="shadow" class="shadow hide"></div>

                <div id="modal1" class="modal1 hide">
                        <p>
                            书名:<input id="title" type='text' name='title' /><br>
                            出版社:<input id="press" type='text' name='press' /><br>
                            出版日期:<input id="date" type='' name='date' /><br>
                        </p>
                            <input type='button' value='提交' onclick="AjaxSend();"/> <span id="errormsg"></span>
                            <input type='button' value='取消' onclick="cancleModal();"/>
                </div>

                <!--对话框显示编辑书籍信息-->
                <div id="editmodal" class="modal1 hide">
                        <h3>对话框编辑</h3>
                        <p>
                            <input id="eid" type='text' name='id' style="display: none"/><br>
                            书名:<input id="etitle" type='text' name='title' /><br>
                            出版社:<input id="epress" type='text' name='press' /><br>
                            出版日期:<input id="edate" type='' name='date' /><br>
                        </p>
                        <input type='button' value='提交' onclick='editAjaxSend();'/>
                        <span id="errormsg"></span>
                        <input type='button' value='取消' onclick='cancleModal();'/>

                </div>
            </div>

        </div>

    </div>
<div class="pg-body">
    <div class="menus">
        <a>书籍管理</a>
        <a href="/booklist/showwriter/">作者管理</a>
        <a href="/booklist/showhero">英雄管理</a>
    </div>

</div>

<!--函数-->
<script type="text/javascript">
    function cancleModal(){
        document.getElementById('shadow').classList.add('hide');
        document.getElementById('modal1').classList.add('hide');
        document.getElementById('editmodal').classList.add('hide');


    }

    function showModal(){
        document.getElementById('shadow').classList.remove('hide');
        document.getElementById('modal1').classList.remove('hide');
    }

    function AjaxSend(){
        $.ajax(
            {url:'/booklist/windowaddbook/',
            type:'POST',
            data:{'title':$('#title').val(),'press':$('#press').val(),'date':$('#date').val(),},
            success:function (data){
                console.log(data);
                if (data=='OK'){
                    location.href='/booklist/showbooks/';
                }else {
                    $('#errormsg').text(data);
                }
            }
        })

    }


    function modelEdit(ths){
        document.getElementById('shadow').classList.remove('hide');
        document.getElementById('editmodal').classList.remove('hide');
        var row = $(ths).parent().prevAll();

        var content = $(row[3]).text();
        $('#eid').val(content);

        var content = $(row[2]).text();
        $('#etitle').val(content);


        var content = $(row[1]).text();
        $('#epress').val(content);

        var content = $(row[0]).text();
        $('#edate').val(content);
    }

    function editAjaxSend(){
        var nid = $('#eid').val();
        var title = $('#etitle').val();
        var press = $('#epress').val();
        var date = $('#edate').val();

        $.ajax({
            url:'/booklist/modelEditbook/',
            type: 'POST',
            data:{'nid':nid,'title':title,'press':press,'date':date},

            success:function (arg){
                arg = JSON.parse(arg);
                if (arg.status){
                    location.reload()

                }else{
                    alert(arg.msg);
                }

            }
        })


    }

</script>
<!--对话框属性-->
<style>
        .hide{
            display: none;
        }

        .shadow{
            position: fixed;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
            background-color: black;
            opacity: 0.3;
            z-index: 1030;
        }
        .modal1{
            position: fixed;
            z-index: 1040;
            height: 50%;
            width: 50%;
            top: 300px;
            bottom: 400px;
            background-color: white;
            margin-left: 350px;
            margin-top: -200px;
        }

</style>

</body>
</html>

booklist/templates/booklist/test_jq_get.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>
<script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js">
</script>
<script>
$(document).ready(function(){
	$("button").click(function(){
		$.get("http://127.0.0.1:8000/booklist/books_view",function(data,status){
			console.log(data)
            for ( x in data) {
                console.log(x[1])
            }
		});
	});
});



</script>
</head>
<body>

<button>发送一个 HTTP GET 请求并获取返回结果</button>
<div id="demo"></div>
</body>
</html>

booklist/templates/booklist/vuetest.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Vue 测试实例 - 菜鸟教程(runoob.com)</title>
<script src="https://cdn.staticfile.org/vue/2.4.2/vue.min.js"></script>
<script src="https://cdn.staticfile.org/axios/0.18.0/axios.min.js"></script>
</head>
<body>
<div id="app">
		<h1>[[info.list]]</h1>
		<h1>{{ info.title }}</h1>
        <li v-for="site in info.title">
            [[site.info]]
        </li>
</div>
<script type = "text/javascript">
    new Vue({
        el: '#app',
        delimiters:['[[',']]'],
        data () {
            return {
              info: {
                  list:'',
              }
            }
          },
        mounted () {
            axios
              .get('http://127.0.0.1:8000/booklist/books_view')
              .then(response => {
                  this.info = response.data;
                  console.log(this.info);
              })
              .catch(function (error) { // 请求失败处理
                console.log(error);
              });
          }
    })
</script>
</body>
</html>