mysite/urls.py
from django.conf.urls import url, include

from django.contrib import admin

urlpatterns = [
    url(r'^booklist/', include(('booklist.urls', 'booklist'), namespace='booklist')),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include(('useradmin.urls', 'useradmin'), namespace='useradmin')),
    url(r'^mytest/', include(('mytest.urls', 'mytest'), namespace='mytest')),
    url(r'^bookdrf/', include(('bookdrf.urls', 'bookdrf'), namespace='bookdrf')),

]

mytest/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$',views.myindex,name = 'myindex'),
    url(r'^mylogin/$',views.mylogin,name='mylogin'),
    url(r'^cgpwd/$',views.cgpwd,name='cgpwd'),
    url(r'^test/$', views.cgpwd, name='cgpwd'),
    url(r'^ajtest/$', views.ajtest, name='ajtest'),
    url(r'^repajax/$', views.repajax, name='repajax'),
    url(r'^get_validCode_img/$', views.get_validCode_img, name='get_validCode_img'),
    url(r'^index/$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),



]

mytest/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class UserInfo(AbstractUser):
    uid = models.AutoField(primary_key=True)
    tel = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to='avaters/', default='/avatar/default.png')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    blog = models.OneToOneField(to='Blog', to_field='bid', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.username


class Blog(models.Model):
    bid = models.AutoField(primary_key=True)
    btitle = models.CharField(verbose_name='个人博客标题', max_length=64)
    site_name = models.CharField(verbose_name='站点名称', max_length=64)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.btitle


class Category(models.Model):
    cid = models.AutoField(primary_key=True)
    ctitle = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='bid', on_delete=models.CASCADE)

    def __str__(self):
        return self.ctitle


class Tag(models.Model):
    tid = models.AutoField(primary_key=True)
    ttitle = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='bid', on_delete=models.CASCADE)

    def __str__(self):
        return self.ttitle


class Article(models.Model):
    aid = models.AutoField(primary_key=True)
    atitle = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(verbose_name='文章简介', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    content_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='uid',on_delete=models.CASCADE)
    category = models.ForeignKey(to="Category", to_field='cid',on_delete=models.CASCADE)
    tags = models.ManyToManyField(to='Tag', through='Article2Tag', through_fields=('article', 'tag'))

    def __str__(self):
        return self.atitle


class Article2Tag(models.Model):
    atid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章标题', to='Article', to_field='aid',on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to='Tag',to_field='tid',on_delete=models.CASCADE)

    class Meta:
        unique_together = [('article', 'tag')]

    def __str__(self):
        v = self.article.atitle + '--' + self.tag.ttile
        return v


class ArticleUpDown(models.Model):
    udnid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to='UserInfo', to_field='uid',on_delete=models.CASCADE)
    article = models.ForeignKey(to='Article', to_field='aid',on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [('article', 'user')]


class Comment(models.Model):
    cmid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='aid',on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='uid',on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='评论时间', auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.content

mytest/forms.py
from django import forms
from django.forms import widgets


class registerForm(forms.Form):
	username = forms.CharField(max_length=10,min_length=4,label='用户名',widget=widgets.TextInput(attrs={'class':'form-control'},))
	password = forms.CharField(max_length=20,min_length=6,label='密码',widget=forms.PasswordInput(attrs={'class':'form-control'},))
	repassword = forms.CharField(max_length=20,min_length=6,label='确认密码',widget=forms.PasswordInput(attrs={'class':'form-control'},))
	emial = forms.CharField(max_length=30,min_length=15,label='邮箱',widget=widgets.EmailInput(attrs={'class':'form-control'},))


class loginForm(forms.Form):
	username = forms.CharField(max_length=10,label='用户名')
	password = forms.CharField(max_length=20,label='密码',widget=forms.PasswordInput)


class cgpwdForm(forms.Form):
	username = forms.CharField(label='用户名')
	password = forms.CharField(label='密码',widget=forms.PasswordInput)

mytest/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from .forms import registerForm, loginForm, cgpwdForm
import json
from django.http import JsonResponse

from mytest.utils.getValidimg import getValidCode

def get_validCode_img(request):
    dimg = getValidCode(request)

    return HttpResponse(dimg)


def index(request):
    return render(request, 'mytest/index.html')


def register(request):
    rgform = registerForm()
    if request.method == 'GET':
        return render(request, 'mytest/register.html', {'rgform': rgform})
    # User.objects.create(username='runboo',password='123')

    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        User.objects.create(username=username, password=password)

        return HttpResponse(username)


from django.contrib import auth


def mylogin(request):
    # login(request,user)
    loginform = loginForm()
    # u = auth.authenticate(username='admin', password='admin123')
    # print(u)
    if request.method == 'GET':
        return render(request, 'mytest/login.html', {'loginform': loginform})
    else:
        username = request.POST.get('user')
        password = request.POST.get('pwd')
        validCode = request.POST.get('validCode')
        print(username, password)
        response = {'user': None, 'msg': None}
        validCode_string = request.session['validCode_string']
        if validCode.upper() == validCode_string.upper():
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                response['user'] = username
                response['msg'] = '用户验证成功'
            else:
                response['msg'] = 'username or password wrong.'

        else:
            response['msg'] = 'valid wrong'

        return JsonResponse(response)


def cgpwd(request):
    cgform = cgpwdForm()
    if request.method == 'GET':
        return render(request, 'mytest/cgpwd.html', {'cgform': cgform})

    else:
        username = request.POST['username']
        password = request.POST['password']
        user = User.objects.get(username=username)
        print(user)
        user.set_password(password)
        user.save()
        print(user.set_password(password))

        return HttpResponse('ok')

    # valid_num = request.POST.get('valid_num')


#   	keep_str = request.session.get('keep_str')
# print(valid_num)
# return HttpResponse('ok')


def ajtest(request):
    if request.method == 'GET':
        return render(request, 'mytest/ajax_test.html')

    else:
        ret = {'status': True, 'msg': None}
        pdata = request.POST
        ret['msg'] = 'good'
        print(pdata)
        print(ret)

        return HttpResponse(json.dumps(ret))


def repajax(request):
    if request.method == 'GET':
        return HttpResponse('hello')

mytest/templates/mytest/ajax_test.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>
<script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js">
</script>

</head>
<body>
<form>
     <form>
        <input id="p1" class="p1" type="text" value="">
        <input id="btn" class="btn" type="button" value="go">
    </form>
</form>
<button id="btn" onclick="editAjaxSend()">ajax-get</button>

<script>
    var person = {
        firstName:"John",
        lastName:"Doe",
        age:50,
        eyeColor:"blue"
    };

    var sendAjax = {
        type:'post',
        data:{p1:'123'},
        url:'',
        success:function (data){
            console.log(data)
        }
    };


    a = 10;
    function go(){
        $.ajax(sendAjax);
    }

    $('#btn').click(go);




    $(document).ready(function (){
         $('#btn').click(function (){
            {#$('.p1').val('123');#}
            $('.p1').text('1231');
        });
    });



    function editAjaxSend(){
        var nid = 1;
        var title = 'ajax';
        var press = 'P01';
        var date = '2020';

        $.ajax({
            url:'/mytest/ajtest/',
            type: 'POST',
            data:{'nid':nid,'title':title,'press':press,'date':date},

            success:function (arg){
                arg = JSON.parse(arg);
                // console.log(123);
                if (arg.status){
                    // location.reload()
                    console.log('okokok');
                    window.location.href = 'https://www.baidu.com';

                }else{
                    alert(arg.msg);
                }

            }
        })

    }



</script>
</body>
</html>

mytest/templates/mytest/cgpwd.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<script type="text/javascript" src="/static/js/myjs.js"></script>
</head>
<body>
<form action="{% url 'mytest:cgpwd' %}" method="post">
	{{cgform}}<br>
	<input type="" name="" id="p1">
	<input type="button" name="" value="btn" onclick="ck()">
	<input type="submit" value="提交" onclick="ck()">

</form>
</body>
</html>

mytest/templates/mytest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ request.user.username }}
</body>
</html>

mytest/templates/mytest/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="/static/bt/css/bootstrap.css">
    <script type="text/javascript" src="/static/js/myjs.js"></script>
    <script type="text/javascript" src="/static/js/jquery-3.6.0.js"></script>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-3">
            {% csrf_token %}
            <button onclick="setLoginForm()">对齐</button>
            <form action="{% url 'mytest:mylogin' %}" method="post" id="loginform">

                <div class="form-group">
                    <label for="id_username">用户名</label>
                    {{ loginform.username }}<br>
                </div>


                <div class="form-group">
                    <label for="id_password">密码</label>
                    {{ loginform.password }}<br>
                </div>

                {#                验证码#}
                <div class="form-group">
                    <label>验证码</label>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" class="valid_code form-control">
                        </div>
                        <div>
                            <img width="132" height="32" id="imageCode" src="/mytest/get_validCode_img/">
                        </div>

                    </div>

                </div>


                {#	submit form 表单提交#}
                {#	<input type="submit" name="提交">#}

                {#    button 绑定事件，ajax提交#}
                <input type="button" value="提交" class="btn btn-default login_btn"><span class="error pull-right"></span>
                <a href="/mytest/register" class="btn btn-success pull-right">注册</a>
            </form>
        </div>

    </div>

</div>
<script>
    $('#imageCode').click(function (){
    $(this)[0].src+='?';

    })
    //校验验证码
    $('.login_btn').click(function (){
        $.ajax({
            url:"",
            type:'post',
            data:{
                user:$('#id_username').val(),
                pwd:$('#id_password').val(),
                validCode:$('.valid_code').val(),
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()

            },
            success:function (data){
                console.log(data)
                if(data.user){
                    location.href = '/mytest/index'
                }else {
                    $('.error').text(data.msg).css({'color':'red','margin':'10px'});
                    setTimeout(function (){
                        $('.error').text('');
                    },2000)
                }
            }
        })
    })
</script>
</body>
</html>

mytest/templates/mytest/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bt/css/bootstrap.css">
    <script type="text/javascript" src="/static/js/myjs.js"></script>
    <script type="text/javascript" src="/static/js/jquery-3.6.0.js"></script>
	<title></title>
    <style>
        #avatar_iamge{
            margin:10px;
        }

        #avatar {
            display: none;
        }
    </style>
</head>
<body>


<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-offset-3">
            {% csrf_token %}
            <form action="{% url 'mytest:mylogin' %}" method="post" id="loginform">

                {% for foo in rgform %}
                    <div class="form-group">
                    <label for="{{ foo.auto_id }}">{{ foo.label }}</label>
                    {{ foo }}
                    </div>

                {% endfor %}
            <div class="form-group">
                <label for="avatar">头像<img id="avatar_iamge" width="50" height="50" src="/static/images/default.png"></label>
                <input id="avatar" type="file">

            </div>

                <input type="button" value="提交" class="btn btn-default login_btn"><span class="error pull-right"></span>
            </form>
        </div>

    </div>

</div>

<script>
    $('#avatar').change(function (){
        var fileobj = $(this)[0].files[0];
        var ava = document.getElementById('avatar').value;
        console.log(ava);
        var reader = new FileReader();
        reader.readAsDataURL(fileobj)

        reader.onload=function (){
            //jquery方式
            {#$('#avatar_iamge').attr('src',reader.result);#}
            //js方式
            document.getElementById('avatar_iamge').setAttribute('src',reader.result);
        }


    });


    function go (){
        $.ajax({
            type:'post',
            data:{},
            url:'',
            success:function (data){
                console.log(data)
                if(data.user){
                    console.log('ok');
                }else {
                    console.log('error');
                }
            }

        })
    }
    $('.valid_code').click(go)

</script>

</body>
</html>

mytest/templates/mytest/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bt/css/bootstrap.css">
    <script type="text/javascript" src="/static/js/myjs.js"></script>
    <script type="text/javascript" src="/static/js/jquery-3.6.0.js"></script>
</head>
<body>
    <form>
        <input id="p1" class="p1" type="text">
        <input id="btn" class="btn" type="button" value="go">
    </form>


<script>
    $('#btn').click(function (){
        $('.p1').value='132';
    })
</script>
</body>
</html>