mysite/urls.py
from django.conf.urls import url, include

from django.contrib import admin

urlpatterns = [
    url(r'^booklist/', include(('booklist.urls', 'booklist'), namespace='booklist')),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include(('useradmin.urls', 'useradmin'), namespace='useradmin')),
    url(r'^mytest/', include(('mytest.urls', 'mytest'), namespace='mytest')),
    url(r'^bookdrf/', include(('bookdrf.urls', 'bookdrf'), namespace='bookdrf')),

]

useradmin/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'register$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    # url(r'^login2/$', views.login, name='login2'),
    url(r'^jsif/$', views.jsif, name='jsif'),
    url(r'^edituser/$', views.edituser, name='edituser'),
    url(r'^lf/$', views.login_form, name='login_form'),




]

useradmin/models.py
from django.db import models

# Create your models here.

class Group(models.Model):
    gname = models.CharField(max_length=20)

    def __str__(self):
        return self.gname,self.id

class User(models.Model):
    username = models.CharField(max_length=50,default='Jone')
    nickname = models.CharField(max_length=50,default='Jone')
    password = models.CharField(default='123',max_length=50)
    gender = models.IntegerField(default='12')
    group = models.ManyToManyField(Group)
    email = models.CharField(default='123@126.com',max_length=100)

    def __str__(self):
        return self.username

    #     insert into useradmin_user values(1,'hud','hud','admin','1','1','hud@admin.com');
    #     insert into useradmin_group('emp');

useradmin/forms.py
from django import forms
from haystack.forms import SearchForm


class loginForm(forms.Form):
	username = forms.CharField(label='登录名',max_length=10,min_length=4)
	password = forms.CharField(label='密码',widget=forms.PasswordInput,min_length=10,max_length=20)

useradmin/views.py
from functools import wraps

from rest_framework.generics import GenericAPIView
from rest_framework.mixins import CreateModelMixin,RetrieveModelMixin,ListModelMixin,DestroyModelMixin,UpdateModelMixin

from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import User,Group

def jsif(request):
    if request.method == 'GET':
        # return render(request,'useradmin/jsif.html')
        return render(request,'useradmin/jstest.html')
    else:
        s = request.POST.get('name1')
        print(s)
        return HttpResponse(s)
# def check_register(func):
#     def inner(request,*args,**kwargs):
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#
#         if username == '' or password== '':
#             return HttpResponse('用户名或密码不能空')
#         else:
#             return HttpResponse('ok')
        # for i in username:
        #     if i in ['@','#','$','%','&','*','^']:
        #         return HttpResponse('不能含有特殊字符')
        #     else:
        #         return redirect("/user/login")
    # return inner
from .check_user import checkUser

def register(request):
    if request.method == 'GET':
        return render(request,'useradmin/register.html')
    else:
        data = request.POST
        username = data['username']
        pwd = data['password']
        print(data['username'])
        print(data['password'])
        check_result = checkUser(username,pwd)
        if check_result==None:
            User.objects.create(username=data['username'],nickname=data['nickname'],password=data['password'],
                                gender=data['gender'],email=data['email'])
            return redirect('/user/login.html')
        else:
            return HttpResponse(check_result['msg'])




def logout(request):
    rep = redirect('/user/login/')
    rep.delete_cookie('username')
    request.session.flush()
    return rep

def check_login_cookie(func):
    @wraps(func)
    def inner(request, *args, **kwargs):
        #获取cookie
        cookie_value = request.COOKIES.get('username')
        print('check_login_cookie--%s'%cookie_value)
        try:#获取 session
            sessionid = request.session['username']
        except:
            print('没有session')
            sessionid = None
        #如果有session,允许访问url
        if sessionid:
            if cookie_value:
                # 如果存在coookie，继续执行
                return func(request, *args, **kwargs)
            # 如果没有cookie转到登录页面
            else:
                next_url = request.path_info
                return redirect("/user/login".format(next_url))
        else:#如果没有session 则跳转到登录页面
            next_url = request.path_info
            return redirect("/user/login".format(next_url))

    return inner


def check_login_cookie2(request, urls,datas):
    cookie_value = request.COOKIES.get('username')
    print('cookie_value=%s'%cookie_value)
    if cookie_value == "admin":
        # 已经登录，继续执行
        print('*urls=%s'%(urls))
        obj = render(request,urls,datas)
        return obj
    # 没有登录过
    else:
        # ** 即使登录成功也只能跳转到home页面，现在通过在URL中加上next指定跳转的页面
        # 获取当前访问的URL
        next_url = request.path_info
        obj = redirect("/booklist/login".format(next_url))
        return obj


def edituser(request):
    if request.method == 'GET':
        return render(request,'useradmin/edituser.html')
    else:
        pass


def allowed_users(allowed_roles=[]):
    def decorator(view_func):
        def wapper_func(request,*args,**kwargs):
            u = request.COOKIES.get('username')
            uid = User.objects.filter(username=u).values('id')
            if uid:
                uid=uid[0]['id']
            g = Group.objects.filter(user__id=uid).values('gname')
            if g:
                print('111111111111')
                gname = g[0]['gname']
                print('gnamegnamegnamegngnameame',gname)
                print('g=%s,\nrols=%s'%(gname,allowed_roles))

                if gname in allowed_roles:
                    return view_func(request,*args,**kwargs)
                else:
                    return render(request,'useradmin/login.html',{'msg':'没有权限'})
            else:
                return HttpResponse('没有权限<a href="/booklist/showbooks_pagehandle">返回首页</a>')
            return view_func(request,*args,**kwargs)
        return wapper_func
    return decorator


def login(request):
    if request.method == "GET":
        return render(request, 'useradmin/login.html')
    else:
        print('getsession=====',request.session.get('user_id'))
        u = request.POST.get('user')
        p = request.POST.get('password')
        uid = User.objects.filter(username=u).values('id')

        try:
            user = User.objects.get(Q(username=u,password=p))
         
        except:
            return render(request, 'useradmin/login.html', {'msg': '密码或用户名错误'})
            user = None
        #如果验证用户成功，设置cookie和session
        if user:
            print('user=%s,p=%s' % (user.username, user.password))

            obj = redirect('/booklist/showbooks_pagehandle')
            obj.set_cookie('username',u,3600)
            request.session['username'] = u
            return obj

        else:
            # print('123')
            return render(request, 'useradmin/login.html', {'msg': '密码或用户名错误'})


from .forms import loginForm

def login_form(request):
    lf = loginForm()
    print(lf)
    if request.method == 'GET':
        return render(request,'useradmin/login_form.html',{'login_form':lf})

    else:
        return HttpResponse('ok')

useradmin/templates/useradmin/edituser.html
<html></html>

useradmin/templates/useradmin/jsif.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>二级级联查询</title>
</head>
<body>
    <select id="first" onChange="nextChange()">
        <option selected="selected"></option>
        <option>湛江</option>
        <option>深圳</option>
    </select>
    <select id="second">

        <option></option>
    </select>


<script>
    function nextChange()
    {
        var first = document.getElementById("first");
        var second = document.getElementById("second");
        second.options.length = 0; // 清除second下拉框的所有内容
        if(first.selectedIndex == 1)
        {
            second.options.add(new Option("廉江市", "0"));
            second.options.add(new Option("吴川市", "2"));
            second.options.add(new Option("坡头区", "1", false, true));  // 默认选中区
        }

        if(first.selectedIndex == 2)
        {
            second.options.add(new Option("福田区", "0"));
            second.options.add(new Option("罗湖区", "1", false, true));  // 默认选中区
            second.options.add(new Option("南山区", "2"));
        }
    }

</script>
</body>
</html>

useradmin/templates/useradmin/jstest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <button onclick="myFunction()">点击这里</button>
    <p id="demo"></p>
<!--<script>-->
<!--function myFunction(){-->
<!--	var x="";-->
<!--	var time=new Date().getHours();-->
<!--	if (time<20){-->
<!--	 	x="Good day";-->
<!--     }-->
<!--	else{-->
<!-- 		x="Good evening";-->
<!-- 	}-->
<!--	document.getElementById("demo").innerHTML=x;-->
<!--}-->
<!--</script>-->
</head>
<body>
<script>

        function myFunction() {
        var first = document.getElementById("first");
        switch (first.selectedIndex) {
            case 1:
                var obj = document.getElementById("id1");
                obj.setAttribute("readOnly",false);
                obj.value='';
                alert('1-myFunction');
                break;
            case 2:
                alert('2-myFunction')
                var obj = document.getElementById("id2");
                obj.setAttribute("readOnly",false);
                obj.value='';
                break;
            case 3:
                var obj = document.getElementById("id3");
                obj.setAttribute("readOnly",false);
                obj.value='';
                break;
    }

}

     function nextChange() {
        var first = document.getElementById("first");
        if(first.selectedIndex == 1)

        {
            var obj2 = document.getElementById("id2");
            obj2.setAttribute();
            alert('1-nextChange');
            obj2.value='';
        }

        if(first.selectedIndex == 2)
        {
            var obj = document.getElementById("id2");
            obj.setAttribute("readOnly",true);
            alert('2-nextChange')

            obj.style.backgroundColor="#d2d2d2";
        }
        if(first.selectedIndex==3){
            var obj = document.getElementById("id3");
            obj.setAttribute("readOnly",true);
            obj.style.backgroundColor="#d2d2d2";
        }
    }


</script>

<!--<script>-->
<!--    function nextChange()-->
<!--    {-->
<!--        var first = document.getElementById("first");-->
<!--        if(first.selectedIndex == 1)-->

<!--        {-->
<!--            var obj2 = document.getElementById("id2");-->
<!--            obj2.setAttribute();-->
<!--            alert('11111');-->
<!--            obj2.value='';-->
<!--        }-->

<!--        if(first.selectedIndex == 2)-->
<!--        {-->
<!--            var obj = document.getElementById("id2");-->
<!--            obj.setAttribute("readOnly",true);-->
<!--            obj.style.backgroundColor="#d2d2d2";-->
<!--        }-->
<!--        if(first.selectedIndex==3){-->
<!--            var obj = document.getElementById("id3");-->
<!--            obj.setAttribute("readOnly",true);-->
<!--            obj.style.backgroundColor="#d2d2d2";-->
<!--        }-->
<!--    }-->

<!--</script>-->


<style>
    input{
    disabled:"disabled";
    style:"background:#CCCCCC";

    }

    label{
        color: #0a53be;
    }
</style>

    <script type="text/javascript">
        function readonly(){
            // document.getElementById("id1").disabled = false;
            var obj = document.getElementById("id1");
            obj.setAttribute("readOnly",true);
            obj.style.backgroundColor="#d2d2d2";
        }
    </script>
<form action="{% url 'useradmin:jsif' %}" method="post">
    <label>利率类型</label><br>
    <select name="f" id="first" onchange="nextChange()">
        <option selected="selected"></option>
        <option>1</option>
        <option>2</option>
        <option>3</option>
    </select><br>
    <label>name1</label><input type="text" name="name1" id="id1"><br>
    <label>name2</label><input type="text" name="name2" id="id2"><br>
    <label>name3</label><input class="class1" id="id3" type="text" name="name3"><br>

    <input type="submit" value="提交">

</form>
</body>
</html>

useradmin/templates/useradmin/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>name</title>
</head>
<body>

<form method="POST" action="{% url 'useradmin:login' %}">
    name:<input type='text' name='user' />
    password:<input type='password' name='password' />
    <input type='submit' value='登录' />
    {{msg}}

</form>

</body>
</html>

useradmin/templates/useradmin/login_form.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<form action="{% url 'useradmin:login_form' %}" method="post">
	{%for f in login_form%}
	{{f}}
	{%endfor%}
	<input type="submit" name="提交">
</form>
</body>
</html>

useradmin/templates/useradmin/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'useradmin:register' %}" method="post">
    username:<input type="text" name="username"><br>
    nickname:<input type="text" name="nickname"><br>
    passwrod:<input type="password" name="password"><br>
    gender:<input type="gender" name="gender"><br>
    email:<input type="email" name="email"><br>
    <input type="submit" value="提交">
</form>
</body>
</html>